### ISSUE TITLE
England or Scotland or Wales

### ISSUE THREAD

**Issue by brogan89** [cristiroma/countries#20]
Hey, I really appreciate what you have done here, it has saved me a lot work.
I am curious, however, why there is no Scotland or England or Wales within the 250 items?
I understand they are apart of the United Kingdom object, but they are also their own individual countries respectively.

**Comment by cristiroma** [comment]
Dear @brogan89 sorry for the late answer, the list is build around ISO 3166 code, therefore Scotland and Wales do not have a separate ISO code. According to this page https://en.wikipedia.org/wiki/ISO_3166-2:GB - they are using the GB. Do you have any other source of information?

Thanks.

**Comment by brogan89** [comment]
Thanks for the reply. I see how you've done it. That's cool, I was curious is all. I was thinking of something like the Olympics where they each fly their own flag. I was using this library for a similar situation.

**Comment by LuckyLimey** [comment]
What is the solution for this? Am sure the Welsh and Scottish are not impressed....

**Comment by cristiroma** [comment]
@LuckyLimey I did more research and found the individual codes, https://en.m.wikipedia.org/wiki/ISO_3166-2:GB#Countries_and_province

I'll add them to the list

**Comment by cristiroma** [comment]
I will recall back adding England separately, since I'm moving towards the M49 UN standard for country names (https://unstats.un.org/unsd/methodology/m49/#fn2) - the official name is "United Kingdom of Great Britain and Northern Ireland" with the `GBR` and respectively `GB` ISO codes.
