### ISSUE TITLE
Not working with laravel 5.4

### ISSUE THREAD

**Issue by jagadishQison** [cristiroma/countries#21]
Getting below Issue when executing composer update commond

PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::share() in C:\xampp\htdocs\gdaccess_james\vendor\thedevsaddam\world-countries\src\WorldCountriesServiceProvider.php on line 35
Script php artisan optimize handling the post-update-cmd event returned with error code 255

**Comment by cristiroma** [comment]
@jagadishQison I'm not sure I understand your exact issue, can you please detail?
