### ISSUE TITLE
The dividing method of seven continents is correct ？

### ISSUE THREAD

**Issue by DamonGG** [cristiroma/countries#22]
The world is recognized：
> North America, South America, Africa, Antarctica, Australia (Oceania), Europe, and Asia.

But in your region table:
```
1. Africa
2. Asia and the Pacific
3. Europe
4. Latin America and the Caribbean
5. North America
6. Polar: Arctic
7. West Asia
```
I want to know the reason of your divided

**Comment by cristiroma** [comment]
Greetings @DamonGG the reason behind is that I've started the project around United Nations project which has a specific geopolitical break-down of members. Available here: https://unstats.un.org/unsd/methodology/m49/

I might consider increasing the scope to a more geographical-oriented data-set.

**Comment by DamonGG** [comment]
@cristiroma Thanks for your explanation and your codes.
