### ISSUE TITLE
Add Catalonia country

### ISSUE THREAD

**Issue by gtailly** [cristiroma/countries#31]
Hey guys, 

Thanks for the API, could you add Catalonia as a country ? 

Thanks in advance

**Comment by cristiroma** [comment]
I'm sorry if you're not going to like the resolution, but I am going to close this ticket. Catalonia is not an internationally recognized body and there is no official ISO 3166 alpha 2 or alpha 3 code. (There is `ES-CT` code autonomus community declared https://en.wikipedia.org/wiki/ISO_3166-2:ES). For your project I suggest to fork the repository and append your own data.

**Comment by marlonlom** [comment]
>_A country is defined as a geographical area that is identified as a distinct national body. It is usually characterized by its government. Catalonia does not meet this definition and therefore cannot be categorized as a country._

URL link: [Is Catalonia A Country? by worldatlas.com](https://www.worldatlas.com/articles/is-catalonia-a-country.html)
